# Generated by Django 5.0 on 2025-09-07 03:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_reviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='movies',
            new_name='movie',
        ),
    ]
